package com.uuabc.classroomlib.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.uuabc.classroomlib.model.db.LottieRecord;

import com.uuabc.classroomlib.model.db.LottieRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lottieRecordDaoConfig;

    private final LottieRecordDao lottieRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lottieRecordDaoConfig = daoConfigMap.get(LottieRecordDao.class).clone();
        lottieRecordDaoConfig.initIdentityScope(type);

        lottieRecordDao = new LottieRecordDao(lottieRecordDaoConfig, this);

        registerDao(LottieRecord.class, lottieRecordDao);
    }
    
    public void clear() {
        lottieRecordDaoConfig.clearIdentityScope();
    }

    public LottieRecordDao getLottieRecordDao() {
        return lottieRecordDao;
    }

}
