package com.uuabc.classroomlib.model.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig logEntityDaoConfig;
    private final DaoConfig lottieRecordDaoConfig;

    private final LogEntityDao logEntityDao;
    private final LottieRecordDao lottieRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        logEntityDaoConfig = daoConfigMap.get(LogEntityDao.class).clone();
        logEntityDaoConfig.initIdentityScope(type);

        lottieRecordDaoConfig = daoConfigMap.get(LottieRecordDao.class).clone();
        lottieRecordDaoConfig.initIdentityScope(type);

        logEntityDao = new LogEntityDao(logEntityDaoConfig, this);
        lottieRecordDao = new LottieRecordDao(lottieRecordDaoConfig, this);

        registerDao(LogEntity.class, logEntityDao);
        registerDao(LottieRecord.class, lottieRecordDao);
    }

    public void clear() {
        logEntityDaoConfig.clearIdentityScope();
        lottieRecordDaoConfig.clearIdentityScope();
    }

    public LogEntityDao getLogEntityDao() {
        return logEntityDao;
    }

    public LottieRecordDao getLottieRecordDao() {
        return lottieRecordDao;
    }

}
